# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true

# Mod Properties
mod.id=combatify
mod.name=Combatify
mod.description=A mod library and standalone mod that adds features from the combat test snapshots
mod.version = 1.4.0
mod.group = net.atlas
mod.archives_base = combatify
mod.sub_version = release
mod.license=LGPL-2.1-only

# Dependencies
deps.minecraft=[VERSIONED]
deps.rhino_version=1.8.0
deps.jackson_version=2.18.8
deps.dep_defaulted=1.3.3

# Reflink: https://fabricmc.net/develop/
deps.fabric-api=[VERSIONED]
deps.fabric-loader=0.19.3
loomx.loom_version=1.17-SNAPSHOT

# Ditto: https://projects.neoforged.net/
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=
