deps.minecraft=1.21.1
deps.neoforge=21.1.235

mod.mc_dep_forgelike=[1.21.1, 1.21.4]

deps.java=21
deps.forgified-fabric-api=0.116.7+2.2.4+1.21.1
deps.toml4j=0.7.2
deps.rhino=1.8.0
deps.sodium=mc1.21.1-0.6.13-neoforge
deps.atlas_core=1.1.3-1.21.1
deps.defaulted=1.3.1-1.21.1-NeoForge
deps.viafabricplus=3.4.9
deps.modmenu=11.0.1
deps.cloth-config=15.0.127
deps.packet_tweaker=0.5.5+1.21
deps.polymer=0.9.18+1.21.1
deps.appleskin=mc1.21-3.0.7
