deps.minecraft=26.2

mod.mc_dep_fabric=26.2

deps.java=25
deps.fabric-api=0.154.2+26.2
deps.modmenu=20.0.0
deps.cloth-config=26.2.155
deps.sodium=mc26.2-0.9.1-beta.4-fabric
deps.atlas_core=1.1.3-26.2
deps.defaulted=1.2.3-26.1-Fabric-HF1
deps.viafabricplus=4.6.1
deps.cookeymod=1.7.18+26.2
deps.polymer=0.17.2+26.2
deps.appleskin=mc26.2-3.0.10
deps.jackson=2.18.8
deps.rhino=1.8.0
